version: '3.9'
services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'warehouses_db'
    ports:
      - "5432:5432"


  app:
    build: .
    container_name: app
    image: app
    environment:
      PG_URL: 'postgres://admin:password@postgres:5432/warehouses_db'
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pg-data: